/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tmu_core_Nauty */

#ifndef _Included_org_tmu_core_Nauty
#define _Included_org_tmu_core_Nauty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tmu_core_Nauty
 * Method:    canonize
 * Signature: ([Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_tmu_core_Nauty_canonize
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
